/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  BulkTransferSystem,
  BulkTransferSystemInterface,
} from "../BulkTransferSystem";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IWorld",
        name: "_world",
        type: "address",
      },
      {
        internalType: "address",
        name: "_components",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "arguments",
        type: "bytes",
      },
    ],
    name: "execute",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "items",
        type: "uint256[]",
      },
      {
        internalType: "uint256",
        name: "receiver",
        type: "uint256",
      },
    ],
    name: "executeTyped",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class BulkTransferSystem__factory {
  static readonly abi = _abi;
  static createInterface(): BulkTransferSystemInterface {
    return new utils.Interface(_abi) as BulkTransferSystemInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BulkTransferSystem {
    return new Contract(address, _abi, signerOrProvider) as BulkTransferSystem;
  }
}
