/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IPayableSystem,
  IPayableSystemInterface,
} from "../IPayableSystem";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "arguments",
        type: "bytes",
      },
    ],
    name: "execute",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IPayableSystem__factory {
  static readonly abi = _abi;
  static createInterface(): IPayableSystemInterface {
    return new utils.Interface(_abi) as IPayableSystemInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPayableSystem {
    return new Contract(address, _abi, signerOrProvider) as IPayableSystem;
  }
}
