/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ISystem, ISystemInterface } from "../ISystem";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "arguments",
        type: "bytes",
      },
    ],
    name: "execute",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ISystem__factory {
  static readonly abi = _abi;
  static createInterface(): ISystemInterface {
    return new utils.Interface(_abi) as ISystemInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISystem {
    return new Contract(address, _abi, signerOrProvider) as ISystem;
  }
}
