/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type WorldQueryFragmentStruct = {
  queryType: BigNumberish;
  componentId: BigNumberish;
  value: BytesLike;
};

export type WorldQueryFragmentStructOutput = [number, BigNumber, string] & {
  queryType: number;
  componentId: BigNumber;
  value: string;
};

export interface WorldInterface extends utils.Interface {
  contractName: "World";
  functions: {
    "components()": FunctionFragment;
    "getComponent(uint256)": FunctionFragment;
    "getComponentIdFromAddress(address)": FunctionFragment;
    "getNumEntities()": FunctionFragment;
    "getSystemAddress(uint256)": FunctionFragment;
    "getUniqueEntityId()": FunctionFragment;
    "hasEntity(uint256)": FunctionFragment;
    "init()": FunctionFragment;
    "query((uint8,uint256,bytes)[])": FunctionFragment;
    "register()": FunctionFragment;
    "registerComponent(address,uint256)": FunctionFragment;
    "registerComponentValueRemoved(uint256)": FunctionFragment;
    "registerComponentValueSet(address,uint256,bytes)": FunctionFragment;
    "registerSystem(address,uint256)": FunctionFragment;
    "systems()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "components",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getComponent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getComponentIdFromAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getNumEntities",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSystemAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUniqueEntityId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasEntity",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "init", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "query",
    values: [WorldQueryFragmentStruct[]]
  ): string;
  encodeFunctionData(functionFragment: "register", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerComponent",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerComponentValueRemoved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerComponentValueSet",
    values: [string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerSystem",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "systems", values?: undefined): string;

  decodeFunctionResult(functionFragment: "components", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getComponent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getComponentIdFromAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNumEntities",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSystemAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUniqueEntityId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasEntity", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "query", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerComponent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerComponentValueRemoved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerComponentValueSet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerSystem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "systems", data: BytesLike): Result;

  events: {
    "ComponentValueRemoved(uint256,address,uint256)": EventFragment;
    "ComponentValueSet(uint256,address,uint256,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ComponentValueRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ComponentValueSet"): EventFragment;
}

export type ComponentValueRemovedEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  { componentId: BigNumber; component: string; entity: BigNumber }
>;

export type ComponentValueRemovedEventFilter =
  TypedEventFilter<ComponentValueRemovedEvent>;

export type ComponentValueSetEvent = TypedEvent<
  [BigNumber, string, BigNumber, string],
  { componentId: BigNumber; component: string; entity: BigNumber; data: string }
>;

export type ComponentValueSetEventFilter =
  TypedEventFilter<ComponentValueSetEvent>;

export interface World extends BaseContract {
  contractName: "World";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: WorldInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    components(overrides?: CallOverrides): Promise<[string]>;

    getComponent(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getComponentIdFromAddress(
      componentAddr: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getNumEntities(overrides?: CallOverrides): Promise<[BigNumber]>;

    getSystemAddress(
      systemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getUniqueEntityId(overrides?: CallOverrides): Promise<[BigNumber]>;

    hasEntity(
      entity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    init(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    query(
      worldQueryFragments: WorldQueryFragmentStruct[],
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    register(overrides?: CallOverrides): Promise<[string]>;

    registerComponent(
      componentAddr: string,
      id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "registerComponentValueRemoved(uint256)"(
      entity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "registerComponentValueRemoved(address,uint256)"(
      component: string,
      entity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "registerComponentValueSet(address,uint256,bytes)"(
      component: string,
      entity: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "registerComponentValueSet(uint256,bytes)"(
      entity: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    registerSystem(
      systemAddr: string,
      id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    systems(overrides?: CallOverrides): Promise<[string]>;
  };

  components(overrides?: CallOverrides): Promise<string>;

  getComponent(id: BigNumberish, overrides?: CallOverrides): Promise<string>;

  getComponentIdFromAddress(
    componentAddr: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getNumEntities(overrides?: CallOverrides): Promise<BigNumber>;

  getSystemAddress(
    systemId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getUniqueEntityId(overrides?: CallOverrides): Promise<BigNumber>;

  hasEntity(entity: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

  init(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  query(
    worldQueryFragments: WorldQueryFragmentStruct[],
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  register(overrides?: CallOverrides): Promise<string>;

  registerComponent(
    componentAddr: string,
    id: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "registerComponentValueRemoved(uint256)"(
    entity: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "registerComponentValueRemoved(address,uint256)"(
    component: string,
    entity: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "registerComponentValueSet(address,uint256,bytes)"(
    component: string,
    entity: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "registerComponentValueSet(uint256,bytes)"(
    entity: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  registerSystem(
    systemAddr: string,
    id: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  systems(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    components(overrides?: CallOverrides): Promise<string>;

    getComponent(id: BigNumberish, overrides?: CallOverrides): Promise<string>;

    getComponentIdFromAddress(
      componentAddr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNumEntities(overrides?: CallOverrides): Promise<BigNumber>;

    getSystemAddress(
      systemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getUniqueEntityId(overrides?: CallOverrides): Promise<BigNumber>;

    hasEntity(
      entity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    init(overrides?: CallOverrides): Promise<void>;

    query(
      worldQueryFragments: WorldQueryFragmentStruct[],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    register(overrides?: CallOverrides): Promise<string>;

    registerComponent(
      componentAddr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "registerComponentValueRemoved(uint256)"(
      entity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "registerComponentValueRemoved(address,uint256)"(
      component: string,
      entity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "registerComponentValueSet(address,uint256,bytes)"(
      component: string,
      entity: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "registerComponentValueSet(uint256,bytes)"(
      entity: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    registerSystem(
      systemAddr: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    systems(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "ComponentValueRemoved(uint256,address,uint256)"(
      componentId?: BigNumberish | null,
      component?: string | null,
      entity?: BigNumberish | null
    ): ComponentValueRemovedEventFilter;
    ComponentValueRemoved(
      componentId?: BigNumberish | null,
      component?: string | null,
      entity?: BigNumberish | null
    ): ComponentValueRemovedEventFilter;

    "ComponentValueSet(uint256,address,uint256,bytes)"(
      componentId?: BigNumberish | null,
      component?: string | null,
      entity?: BigNumberish | null,
      data?: null
    ): ComponentValueSetEventFilter;
    ComponentValueSet(
      componentId?: BigNumberish | null,
      component?: string | null,
      entity?: BigNumberish | null,
      data?: null
    ): ComponentValueSetEventFilter;
  };

  estimateGas: {
    components(overrides?: CallOverrides): Promise<BigNumber>;

    getComponent(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getComponentIdFromAddress(
      componentAddr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNumEntities(overrides?: CallOverrides): Promise<BigNumber>;

    getSystemAddress(
      systemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUniqueEntityId(overrides?: CallOverrides): Promise<BigNumber>;

    hasEntity(
      entity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    init(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    query(
      worldQueryFragments: WorldQueryFragmentStruct[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    register(overrides?: CallOverrides): Promise<BigNumber>;

    registerComponent(
      componentAddr: string,
      id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "registerComponentValueRemoved(uint256)"(
      entity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "registerComponentValueRemoved(address,uint256)"(
      component: string,
      entity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "registerComponentValueSet(address,uint256,bytes)"(
      component: string,
      entity: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "registerComponentValueSet(uint256,bytes)"(
      entity: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    registerSystem(
      systemAddr: string,
      id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    systems(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    components(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getComponent(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getComponentIdFromAddress(
      componentAddr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNumEntities(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSystemAddress(
      systemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUniqueEntityId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    hasEntity(
      entity: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    init(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    query(
      worldQueryFragments: WorldQueryFragmentStruct[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    register(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registerComponent(
      componentAddr: string,
      id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "registerComponentValueRemoved(uint256)"(
      entity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "registerComponentValueRemoved(address,uint256)"(
      component: string,
      entity: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "registerComponentValueSet(address,uint256,bytes)"(
      component: string,
      entity: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "registerComponentValueSet(uint256,bytes)"(
      entity: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    registerSystem(
      systemAddr: string,
      id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    systems(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
