// Autogenerated using mud system-types
export const systemToId = {
  BuildSystem: "system.Build",
  BulkSetStateSystem: "ember.system.bulkSetState",
  ClaimSystem: "system.Claim",
  ComponentDevSystem: "ember.system.componentDev",
  CraftSystem: "system.Craft",
  CreativeBuildSystem: "system.CreativeBuild",
  Init2System: "system.Init2",
  InitSystem: "system.Init",
  MineSystem: "system.Mine",
  NameSystem: "system.Name",
  OccurrenceSystem: "system.Occurrence",
  RegisterPluginSystem: "system.RegisterPlugin",
  StakeSystem: "system.Stake",
  TransferSystem: "system.Transfer",
};

export const idToSystem = {
  "system.Build": "BuildSystem",
  "ember.system.bulkSetState": "BulkSetStateSystem",
  "system.Claim": "ClaimSystem",
  "ember.system.componentDev": "ComponentDevSystem",
  "system.Craft": "CraftSystem",
  "system.CreativeBuild": "CreativeBuildSystem",
  "system.Init2": "Init2System",
  "system.Init": "InitSystem",
  "system.Mine": "MineSystem",
  "system.Name": "NameSystem",
  "system.Occurrence": "OccurrenceSystem",
  "system.RegisterPlugin": "RegisterPluginSystem",
  "system.Stake": "StakeSystem",
  "system.Transfer": "TransferSystem",
};
  