// Autogenerated using mud system-types
import { BuildSystem } from "./ethers-contracts/BuildSystem";
import { BulkSetStateSystem } from "./ethers-contracts/BulkSetStateSystem";
import { BulkStakeSystem } from "./ethers-contracts/BulkStakeSystem";
import { BulkTransferSystem } from "./ethers-contracts/BulkTransferSystem";
import { ClaimSystem } from "./ethers-contracts/ClaimSystem";
import { ComponentDevSystem } from "./ethers-contracts/ComponentDevSystem";
import { CraftSystem } from "./ethers-contracts/CraftSystem";
import { CreativeBuildSystem } from "./ethers-contracts/CreativeBuildSystem";
import { Init2System } from "./ethers-contracts/Init2System";
import { InitSystem } from "./ethers-contracts/InitSystem";
import { MineSystem } from "./ethers-contracts/MineSystem";
import { NameSystem } from "./ethers-contracts/NameSystem";
import { OccurrenceSystem } from "./ethers-contracts/OccurrenceSystem";
import { StakeSystem } from "./ethers-contracts/StakeSystem";
import { TransferSystem } from "./ethers-contracts/TransferSystem";
 
export type SystemTypes = {
  "system.Build": BuildSystem;
  "ember.system.bulkSetState": BulkSetStateSystem;
  "system.BulkStake": BulkStakeSystem;
  "system.BulkTransfer": BulkTransferSystem;
  "system.Claim": ClaimSystem;
  "ember.system.componentDev": ComponentDevSystem;
  "system.Craft": CraftSystem;
  "system.CreativeBuild": CreativeBuildSystem;
  "system.Init2": Init2System;
  "system.Init": InitSystem;
  "system.Mine": MineSystem;
  "system.Name": NameSystem;
  "system.Occurrence": OccurrenceSystem;
  "system.Stake": StakeSystem;
  "system.Transfer": TransferSystem;
};
